package com.baoxue.db;

// Generated 2012-12-4 10:19:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDoPackageUpdateLog generated by hbm2java
 */
@Entity
@Table(name = "T_DO_PACKAGE_UPDATE_LOG", catalog = "baoxue")
public class TDoPackageUpdateLog implements java.io.Serializable {

	private String CId;
	private String CPackageUpdateId;
	private String CDeviceId;
	private Date CTime;
	private String CIp;

	public TDoPackageUpdateLog() {
	}

	public TDoPackageUpdateLog(String CId, String CPackageUpdateId,
			String CDeviceId, Date CTime, String CIp) {
		this.CId = CId;
		this.CPackageUpdateId = CPackageUpdateId;
		this.CDeviceId = CDeviceId;
		this.CTime = CTime;
		this.CIp = CIp;
	}

	@Id
	@Column(name = "C_ID", unique = true, nullable = false, length = 36)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "C_PACKAGE_UPDATE_ID", nullable = false, length = 36)
	public String getCPackageUpdateId() {
		return this.CPackageUpdateId;
	}

	public void setCPackageUpdateId(String CPackageUpdateId) {
		this.CPackageUpdateId = CPackageUpdateId;
	}

	@Column(name = "C_DEVICE_ID", nullable = false, length = 36)
	public String getCDeviceId() {
		return this.CDeviceId;
	}

	public void setCDeviceId(String CDeviceId) {
		this.CDeviceId = CDeviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C_TIME", nullable = false, length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "C_IP", nullable = false, length = 27)
	public String getCIp() {
		return this.CIp;
	}

	public void setCIp(String CIp) {
		this.CIp = CIp;
	}

}
