package com.baoxue.db;

// Generated 2012-11-19 12:57:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDoTaskLog generated by hbm2java
 */
@Entity
@Table(name = "T_DO_TASK_LOG", catalog = "baoxue")
public class TDoTaskLog implements java.io.Serializable {

	private String id;
	private String taskId;
	private String deviceId;
	private Date time;
	private String ip;

	public TDoTaskLog() {
	}

	public TDoTaskLog(String id, String taskId, String deviceId, Date time,
			String ip) {
		this.id = id;
		this.taskId = taskId;
		this.deviceId = deviceId;
		this.time = time;
		this.ip = ip;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TASK_ID", nullable = false, length = 36)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "DEVICE_ID", nullable = false, length = 36)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "IP", nullable = false, length = 27)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
