package com.baoxue.db;

// Generated 2012-12-7 18:49:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDoTaskLog generated by hbm2java
 */
@Entity
@Table(name = "T_DO_TASK_LOG", catalog = "baoxue")
public class TDoTaskLog implements java.io.Serializable {

	private String CId;
	private String CTaskId;
	private String CDeviceId;
	private Date CTime;
	private String CIp;
	private String CDeviceVersion;
	private String CResult;

	public TDoTaskLog() {
	}

	public TDoTaskLog(String CId, String CTaskId, String CDeviceId, Date CTime,
			String CIp, String CDeviceVersion) {
		this.CId = CId;
		this.CTaskId = CTaskId;
		this.CDeviceId = CDeviceId;
		this.CTime = CTime;
		this.CIp = CIp;
		this.CDeviceVersion = CDeviceVersion;
	}

	public TDoTaskLog(String CId, String CTaskId, String CDeviceId, Date CTime,
			String CIp, String CDeviceVersion, String CResult) {
		this.CId = CId;
		this.CTaskId = CTaskId;
		this.CDeviceId = CDeviceId;
		this.CTime = CTime;
		this.CIp = CIp;
		this.CDeviceVersion = CDeviceVersion;
		this.CResult = CResult;
	}

	@Id
	@Column(name = "C_ID", unique = true, nullable = false, length = 36)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "C_TASK_ID", nullable = false, length = 36)
	public String getCTaskId() {
		return this.CTaskId;
	}

	public void setCTaskId(String CTaskId) {
		this.CTaskId = CTaskId;
	}

	@Column(name = "C_DEVICE_ID", nullable = false, length = 36)
	public String getCDeviceId() {
		return this.CDeviceId;
	}

	public void setCDeviceId(String CDeviceId) {
		this.CDeviceId = CDeviceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C_TIME", nullable = false, length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "C_IP", nullable = false, length = 27)
	public String getCIp() {
		return this.CIp;
	}

	public void setCIp(String CIp) {
		this.CIp = CIp;
	}

	@Column(name = "C_DEVICE_VERSION", nullable = false, length = 30)
	public String getCDeviceVersion() {
		return this.CDeviceVersion;
	}

	public void setCDeviceVersion(String CDeviceVersion) {
		this.CDeviceVersion = CDeviceVersion;
	}

	@Column(name = "C_RESULT", length = 65535)
	public String getCResult() {
		return this.CResult;
	}

	public void setCResult(String CResult) {
		this.CResult = CResult;
	}

}
