package com.baoxue.db;

// Generated 2012-11-19 12:57:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPackageUpdate generated by hbm2java
 */
@Entity
@Table(name = "T_PACKAGE_UPDATE", catalog = "baoxue")
public class TPackageUpdate implements java.io.Serializable {

	private String id;
	private String packageName;
	private String oldPackageName;
	private String fileName;
	private int versionCode;
	private String versionName;
	private Date uploadTime;
	private boolean publish;
	private boolean forcesUpdate;

	public TPackageUpdate() {
	}

	public TPackageUpdate(String id, String packageName, String fileName,
			int versionCode, String versionName, Date uploadTime,
			boolean publish, boolean forcesUpdate) {
		this.id = id;
		this.packageName = packageName;
		this.fileName = fileName;
		this.versionCode = versionCode;
		this.versionName = versionName;
		this.uploadTime = uploadTime;
		this.publish = publish;
		this.forcesUpdate = forcesUpdate;
	}

	public TPackageUpdate(String id, String packageName, String oldPackageName,
			String fileName, int versionCode, String versionName,
			Date uploadTime, boolean publish, boolean forcesUpdate) {
		this.id = id;
		this.packageName = packageName;
		this.oldPackageName = oldPackageName;
		this.fileName = fileName;
		this.versionCode = versionCode;
		this.versionName = versionName;
		this.uploadTime = uploadTime;
		this.publish = publish;
		this.forcesUpdate = forcesUpdate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PACKAGE_NAME", nullable = false, length = 100)
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "OLD_PACKAGE_NAME", length = 100)
	public String getOldPackageName() {
		return this.oldPackageName;
	}

	public void setOldPackageName(String oldPackageName) {
		this.oldPackageName = oldPackageName;
	}

	@Column(name = "FILE_NAME", nullable = false, length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "VERSION_CODE", nullable = false)
	public int getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(int versionCode) {
		this.versionCode = versionCode;
	}

	@Column(name = "VERSION_NAME", nullable = false, length = 45)
	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_TIME", nullable = false, length = 19)
	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	@Column(name = "PUBLISH", nullable = false)
	public boolean isPublish() {
		return this.publish;
	}

	public void setPublish(boolean publish) {
		this.publish = publish;
	}

	@Column(name = "FORCES_UPDATE", nullable = false)
	public boolean isForcesUpdate() {
		return this.forcesUpdate;
	}

	public void setForcesUpdate(boolean forcesUpdate) {
		this.forcesUpdate = forcesUpdate;
	}

}
