package com.baoxue.db;

// Generated 2012-11-28 15:32:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTaskItem generated by hbm2java
 */
@Entity
@Table(name = "T_TASK_ITEM", catalog = "baoxue")
public class TTaskItem implements java.io.Serializable {

	private String CId;
	private String CTaskId;
	private String CDescription;
	private String CCommand;
	private String CP1;
	private String CP2;
	private String CP3;
	private String CP4;
	private String CP5;
	private int CIndex;
	private boolean CEnable;

	public TTaskItem() {
	}

	public TTaskItem(String CId, String CTaskId, String CDescription,
			String CCommand, int CIndex, boolean CEnable) {
		this.CId = CId;
		this.CTaskId = CTaskId;
		this.CDescription = CDescription;
		this.CCommand = CCommand;
		this.CIndex = CIndex;
		this.CEnable = CEnable;
	}

	public TTaskItem(String CId, String CTaskId, String CDescription,
			String CCommand, String CP1, String CP2, String CP3, String CP4,
			String CP5, int CIndex, boolean CEnable) {
		this.CId = CId;
		this.CTaskId = CTaskId;
		this.CDescription = CDescription;
		this.CCommand = CCommand;
		this.CP1 = CP1;
		this.CP2 = CP2;
		this.CP3 = CP3;
		this.CP4 = CP4;
		this.CP5 = CP5;
		this.CIndex = CIndex;
		this.CEnable = CEnable;
	}

	@Id
	@Column(name = "C_ID", unique = true, nullable = false, length = 36)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "C_TASK_ID", nullable = false, length = 36)
	public String getCTaskId() {
		return this.CTaskId;
	}

	public void setCTaskId(String CTaskId) {
		this.CTaskId = CTaskId;
	}

	@Column(name = "C_DESCRIPTION", nullable = false)
	public String getCDescription() {
		return this.CDescription;
	}

	public void setCDescription(String CDescription) {
		this.CDescription = CDescription;
	}

	@Column(name = "C_COMMAND", nullable = false, length = 50)
	public String getCCommand() {
		return this.CCommand;
	}

	public void setCCommand(String CCommand) {
		this.CCommand = CCommand;
	}

	@Column(name = "C_P1", length = 200)
	public String getCP1() {
		return this.CP1;
	}

	public void setCP1(String CP1) {
		this.CP1 = CP1;
	}

	@Column(name = "C_P2", length = 200)
	public String getCP2() {
		return this.CP2;
	}

	public void setCP2(String CP2) {
		this.CP2 = CP2;
	}

	@Column(name = "C_P3", length = 200)
	public String getCP3() {
		return this.CP3;
	}

	public void setCP3(String CP3) {
		this.CP3 = CP3;
	}

	@Column(name = "C_P4", length = 200)
	public String getCP4() {
		return this.CP4;
	}

	public void setCP4(String CP4) {
		this.CP4 = CP4;
	}

	@Column(name = "C_P5", length = 200)
	public String getCP5() {
		return this.CP5;
	}

	public void setCP5(String CP5) {
		this.CP5 = CP5;
	}

	@Column(name = "C_INDEX", nullable = false)
	public int getCIndex() {
		return this.CIndex;
	}

	public void setCIndex(int CIndex) {
		this.CIndex = CIndex;
	}

	@Column(name = "C_ENABLE", nullable = false)
	public boolean isCEnable() {
		return this.CEnable;
	}

	public void setCEnable(boolean CEnable) {
		this.CEnable = CEnable;
	}

}
