package com.baoxue.db;

// Generated 2012-11-19 12:57:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTask generated by hbm2java
 */
@Entity
@Table(name = "T_TASK", catalog = "baoxue")
public class TTask implements java.io.Serializable {

	private String id;
	private String name;
	private Date createTime;
	private boolean enable;
	private boolean publish;
	private boolean delete;

	public TTask() {
	}

	public TTask(String id, String name, Date createTime, boolean enable,
			boolean publish, boolean delete) {
		this.id = id;
		this.name = name;
		this.createTime = createTime;
		this.enable = enable;
		this.publish = publish;
		this.delete = delete;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "ENABLE", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	@Column(name = "PUBLISH", nullable = false)
	public boolean isPublish() {
		return this.publish;
	}

	public void setPublish(boolean publish) {
		this.publish = publish;
	}

	@Column(name = "DELETE", nullable = false)
	public boolean isDelete() {
		return this.delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}

}
