package com.baoxue.db;

// Generated 2012-11-28 15:32:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TTask generated by hbm2java
 */
@Entity
@Table(name = "T_TASK", catalog = "baoxue", uniqueConstraints = @UniqueConstraint(columnNames = "C_NAME"))
public class TTask implements java.io.Serializable {

	private String CId;
	private String CName;
	private String CVersionRegex;
	private Date CCreateTime;
	private boolean CPublish;
	private boolean CDelete;

	public TTask() {
	}

	public TTask(String CId, String CName, Date CCreateTime, boolean CPublish,
			boolean CDelete) {
		this.CId = CId;
		this.CName = CName;
		this.CCreateTime = CCreateTime;
		this.CPublish = CPublish;
		this.CDelete = CDelete;
	}

	public TTask(String CId, String CName, String CVersionRegex,
			Date CCreateTime, boolean CPublish, boolean CDelete) {
		this.CId = CId;
		this.CName = CName;
		this.CVersionRegex = CVersionRegex;
		this.CCreateTime = CCreateTime;
		this.CPublish = CPublish;
		this.CDelete = CDelete;
	}

	@Id
	@Column(name = "C_ID", unique = true, nullable = false, length = 36)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "C_NAME", unique = true, nullable = false)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "C_VERSION_REGEX", length = 200)
	public String getCVersionRegex() {
		return this.CVersionRegex;
	}

	public void setCVersionRegex(String CVersionRegex) {
		this.CVersionRegex = CVersionRegex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "C_CREATE_TIME", nullable = false, length = 19)
	public Date getCCreateTime() {
		return this.CCreateTime;
	}

	public void setCCreateTime(Date CCreateTime) {
		this.CCreateTime = CCreateTime;
	}

	@Column(name = "C_PUBLISH", nullable = false)
	public boolean isCPublish() {
		return this.CPublish;
	}

	public void setCPublish(boolean CPublish) {
		this.CPublish = CPublish;
	}

	@Column(name = "C_DELETE", nullable = false)
	public boolean isCDelete() {
		return this.CDelete;
	}

	public void setCDelete(boolean CDelete) {
		this.CDelete = CDelete;
	}

}
