package com.baoxue.db;

// Generated 2012-12-4 10:19:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name = "T_USERS", catalog = "baoxue", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class TUsers implements java.io.Serializable {

	private Integer uid;
	private String username;
	private String nickname;
	private String password;
	private String secques;
	private int spaceid;
	private int gender;
	private int adminid;
	private short groupid;
	private int groupexpiry;
	private String extgroupids;
	private String regip;
	private Date joindate;
	private String lastip;
	private Date lastvisit;
	private Date lastactivity;
	private Date lastpost;
	private int lastpostid;
	private String lastposttitle;
	private int posts;
	private short digestposts;
	private int oltime;
	private int pageviews;
	private int credits;
	private BigDecimal extcredits1;
	private BigDecimal extcredits2;
	private BigDecimal extcredits3;
	private BigDecimal extcredits4;
	private BigDecimal extcredits5;
	private BigDecimal extcredits6;
	private BigDecimal extcredits7;
	private BigDecimal extcredits8;
	private int avatarshowid;
	private String email;
	private String bday;
	private int sigstatus;
	private int tpp;
	private int ppp;
	private short templateid;
	private int pmsound;
	private int showemail;
	private int invisible;
	private int newpm;
	private int newpmcount;
	private int accessmasks;
	private int onlinestate;
	private int newsletter;
	private int wapLimit;

	public TUsers() {
	}

	public TUsers(String username, String nickname, String password,
			String secques, int spaceid, int gender, int adminid,
			short groupid, int groupexpiry, String extgroupids, String regip,
			Date joindate, String lastip, Date lastvisit, Date lastactivity,
			Date lastpost, int lastpostid, String lastposttitle, int posts,
			short digestposts, int oltime, int pageviews, int credits,
			BigDecimal extcredits1, BigDecimal extcredits2,
			BigDecimal extcredits3, BigDecimal extcredits4,
			BigDecimal extcredits5, BigDecimal extcredits6,
			BigDecimal extcredits7, BigDecimal extcredits8, int avatarshowid,
			String email, String bday, int sigstatus, int tpp, int ppp,
			short templateid, int pmsound, int showemail, int invisible,
			int newpm, int newpmcount, int accessmasks, int onlinestate,
			int newsletter, int wapLimit) {
		this.username = username;
		this.nickname = nickname;
		this.password = password;
		this.secques = secques;
		this.spaceid = spaceid;
		this.gender = gender;
		this.adminid = adminid;
		this.groupid = groupid;
		this.groupexpiry = groupexpiry;
		this.extgroupids = extgroupids;
		this.regip = regip;
		this.joindate = joindate;
		this.lastip = lastip;
		this.lastvisit = lastvisit;
		this.lastactivity = lastactivity;
		this.lastpost = lastpost;
		this.lastpostid = lastpostid;
		this.lastposttitle = lastposttitle;
		this.posts = posts;
		this.digestposts = digestposts;
		this.oltime = oltime;
		this.pageviews = pageviews;
		this.credits = credits;
		this.extcredits1 = extcredits1;
		this.extcredits2 = extcredits2;
		this.extcredits3 = extcredits3;
		this.extcredits4 = extcredits4;
		this.extcredits5 = extcredits5;
		this.extcredits6 = extcredits6;
		this.extcredits7 = extcredits7;
		this.extcredits8 = extcredits8;
		this.avatarshowid = avatarshowid;
		this.email = email;
		this.bday = bday;
		this.sigstatus = sigstatus;
		this.tpp = tpp;
		this.ppp = ppp;
		this.templateid = templateid;
		this.pmsound = pmsound;
		this.showemail = showemail;
		this.invisible = invisible;
		this.newpm = newpm;
		this.newpmcount = newpmcount;
		this.accessmasks = accessmasks;
		this.onlinestate = onlinestate;
		this.newsletter = newsletter;
		this.wapLimit = wapLimit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "nickname", nullable = false, length = 20)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "secques", nullable = false, length = 8)
	public String getSecques() {
		return this.secques;
	}

	public void setSecques(String secques) {
		this.secques = secques;
	}

	@Column(name = "spaceid", nullable = false)
	public int getSpaceid() {
		return this.spaceid;
	}

	public void setSpaceid(int spaceid) {
		this.spaceid = spaceid;
	}

	@Column(name = "gender", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	@Column(name = "adminid", nullable = false)
	public int getAdminid() {
		return this.adminid;
	}

	public void setAdminid(int adminid) {
		this.adminid = adminid;
	}

	@Column(name = "groupid", nullable = false)
	public short getGroupid() {
		return this.groupid;
	}

	public void setGroupid(short groupid) {
		this.groupid = groupid;
	}

	@Column(name = "groupexpiry", nullable = false)
	public int getGroupexpiry() {
		return this.groupexpiry;
	}

	public void setGroupexpiry(int groupexpiry) {
		this.groupexpiry = groupexpiry;
	}

	@Column(name = "extgroupids", nullable = false, length = 60)
	public String getExtgroupids() {
		return this.extgroupids;
	}

	public void setExtgroupids(String extgroupids) {
		this.extgroupids = extgroupids;
	}

	@Column(name = "regip", nullable = false, length = 15)
	public String getRegip() {
		return this.regip;
	}

	public void setRegip(String regip) {
		this.regip = regip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "joindate", nullable = false, length = 19)
	public Date getJoindate() {
		return this.joindate;
	}

	public void setJoindate(Date joindate) {
		this.joindate = joindate;
	}

	@Column(name = "lastip", nullable = false, length = 15)
	public String getLastip() {
		return this.lastip;
	}

	public void setLastip(String lastip) {
		this.lastip = lastip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastvisit", nullable = false, length = 19)
	public Date getLastvisit() {
		return this.lastvisit;
	}

	public void setLastvisit(Date lastvisit) {
		this.lastvisit = lastvisit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastactivity", nullable = false, length = 19)
	public Date getLastactivity() {
		return this.lastactivity;
	}

	public void setLastactivity(Date lastactivity) {
		this.lastactivity = lastactivity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastpost", nullable = false, length = 19)
	public Date getLastpost() {
		return this.lastpost;
	}

	public void setLastpost(Date lastpost) {
		this.lastpost = lastpost;
	}

	@Column(name = "lastpostid", nullable = false)
	public int getLastpostid() {
		return this.lastpostid;
	}

	public void setLastpostid(int lastpostid) {
		this.lastpostid = lastpostid;
	}

	@Column(name = "lastposttitle", nullable = false, length = 60)
	public String getLastposttitle() {
		return this.lastposttitle;
	}

	public void setLastposttitle(String lastposttitle) {
		this.lastposttitle = lastposttitle;
	}

	@Column(name = "posts", nullable = false)
	public int getPosts() {
		return this.posts;
	}

	public void setPosts(int posts) {
		this.posts = posts;
	}

	@Column(name = "digestposts", nullable = false)
	public short getDigestposts() {
		return this.digestposts;
	}

	public void setDigestposts(short digestposts) {
		this.digestposts = digestposts;
	}

	@Column(name = "oltime", nullable = false)
	public int getOltime() {
		return this.oltime;
	}

	public void setOltime(int oltime) {
		this.oltime = oltime;
	}

	@Column(name = "pageviews", nullable = false)
	public int getPageviews() {
		return this.pageviews;
	}

	public void setPageviews(int pageviews) {
		this.pageviews = pageviews;
	}

	@Column(name = "credits", nullable = false)
	public int getCredits() {
		return this.credits;
	}

	public void setCredits(int credits) {
		this.credits = credits;
	}

	@Column(name = "extcredits1", nullable = false, precision = 18)
	public BigDecimal getExtcredits1() {
		return this.extcredits1;
	}

	public void setExtcredits1(BigDecimal extcredits1) {
		this.extcredits1 = extcredits1;
	}

	@Column(name = "extcredits2", nullable = false, precision = 18)
	public BigDecimal getExtcredits2() {
		return this.extcredits2;
	}

	public void setExtcredits2(BigDecimal extcredits2) {
		this.extcredits2 = extcredits2;
	}

	@Column(name = "extcredits3", nullable = false, precision = 18)
	public BigDecimal getExtcredits3() {
		return this.extcredits3;
	}

	public void setExtcredits3(BigDecimal extcredits3) {
		this.extcredits3 = extcredits3;
	}

	@Column(name = "extcredits4", nullable = false, precision = 18)
	public BigDecimal getExtcredits4() {
		return this.extcredits4;
	}

	public void setExtcredits4(BigDecimal extcredits4) {
		this.extcredits4 = extcredits4;
	}

	@Column(name = "extcredits5", nullable = false, precision = 18)
	public BigDecimal getExtcredits5() {
		return this.extcredits5;
	}

	public void setExtcredits5(BigDecimal extcredits5) {
		this.extcredits5 = extcredits5;
	}

	@Column(name = "extcredits6", nullable = false, precision = 18)
	public BigDecimal getExtcredits6() {
		return this.extcredits6;
	}

	public void setExtcredits6(BigDecimal extcredits6) {
		this.extcredits6 = extcredits6;
	}

	@Column(name = "extcredits7", nullable = false, precision = 18)
	public BigDecimal getExtcredits7() {
		return this.extcredits7;
	}

	public void setExtcredits7(BigDecimal extcredits7) {
		this.extcredits7 = extcredits7;
	}

	@Column(name = "extcredits8", nullable = false, precision = 18)
	public BigDecimal getExtcredits8() {
		return this.extcredits8;
	}

	public void setExtcredits8(BigDecimal extcredits8) {
		this.extcredits8 = extcredits8;
	}

	@Column(name = "avatarshowid", nullable = false)
	public int getAvatarshowid() {
		return this.avatarshowid;
	}

	public void setAvatarshowid(int avatarshowid) {
		this.avatarshowid = avatarshowid;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "bday", nullable = false, length = 10)
	public String getBday() {
		return this.bday;
	}

	public void setBday(String bday) {
		this.bday = bday;
	}

	@Column(name = "sigstatus", nullable = false)
	public int getSigstatus() {
		return this.sigstatus;
	}

	public void setSigstatus(int sigstatus) {
		this.sigstatus = sigstatus;
	}

	@Column(name = "tpp", nullable = false)
	public int getTpp() {
		return this.tpp;
	}

	public void setTpp(int tpp) {
		this.tpp = tpp;
	}

	@Column(name = "ppp", nullable = false)
	public int getPpp() {
		return this.ppp;
	}

	public void setPpp(int ppp) {
		this.ppp = ppp;
	}

	@Column(name = "templateid", nullable = false)
	public short getTemplateid() {
		return this.templateid;
	}

	public void setTemplateid(short templateid) {
		this.templateid = templateid;
	}

	@Column(name = "pmsound", nullable = false)
	public int getPmsound() {
		return this.pmsound;
	}

	public void setPmsound(int pmsound) {
		this.pmsound = pmsound;
	}

	@Column(name = "showemail", nullable = false)
	public int getShowemail() {
		return this.showemail;
	}

	public void setShowemail(int showemail) {
		this.showemail = showemail;
	}

	@Column(name = "invisible", nullable = false)
	public int getInvisible() {
		return this.invisible;
	}

	public void setInvisible(int invisible) {
		this.invisible = invisible;
	}

	@Column(name = "newpm", nullable = false)
	public int getNewpm() {
		return this.newpm;
	}

	public void setNewpm(int newpm) {
		this.newpm = newpm;
	}

	@Column(name = "newpmcount", nullable = false)
	public int getNewpmcount() {
		return this.newpmcount;
	}

	public void setNewpmcount(int newpmcount) {
		this.newpmcount = newpmcount;
	}

	@Column(name = "accessmasks", nullable = false)
	public int getAccessmasks() {
		return this.accessmasks;
	}

	public void setAccessmasks(int accessmasks) {
		this.accessmasks = accessmasks;
	}

	@Column(name = "onlinestate", nullable = false)
	public int getOnlinestate() {
		return this.onlinestate;
	}

	public void setOnlinestate(int onlinestate) {
		this.onlinestate = onlinestate;
	}

	@Column(name = "newsletter", nullable = false)
	public int getNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(int newsletter) {
		this.newsletter = newsletter;
	}

	@Column(name = "wap_limit", nullable = false)
	public int getWapLimit() {
		return this.wapLimit;
	}

	public void setWapLimit(int wapLimit) {
		this.wapLimit = wapLimit;
	}

}
