package com.baoxue.db;

// Generated 2012-11-28 15:32:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VTaskLog generated by hbm2java
 */
@Entity
@Table(name = "v_task_log", catalog = "baoxue")
public class VTaskLog implements java.io.Serializable {

	private VTaskLogId id;

	public VTaskLog() {
	}

	public VTaskLog(VTaskLogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "CId", column = @Column(name = "C_ID", length = 36)),
			@AttributeOverride(name = "CTaskId", column = @Column(name = "C_TASK_ID", nullable = false, length = 36)),
			@AttributeOverride(name = "CName", column = @Column(name = "C_NAME", nullable = false)),
			@AttributeOverride(name = "CVersionRegex", column = @Column(name = "C_VERSION_REGEX", length = 200)),
			@AttributeOverride(name = "CCreateTime", column = @Column(name = "C_CREATE_TIME", nullable = false, length = 19)),
			@AttributeOverride(name = "CPublish", column = @Column(name = "C_PUBLISH", nullable = false)),
			@AttributeOverride(name = "CDelete", column = @Column(name = "C_DELETE", nullable = false)),
			@AttributeOverride(name = "CDeviceId", column = @Column(name = "C_DEVICE_ID", length = 36)),
			@AttributeOverride(name = "CTime", column = @Column(name = "C_TIME", length = 19)),
			@AttributeOverride(name = "CIp", column = @Column(name = "C_IP", length = 27)),
			@AttributeOverride(name = "CDeviceVersion", column = @Column(name = "C_DEVICE_VERSION", length = 30)) })
	public VTaskLogId getId() {
		return this.id;
	}

	public void setId(VTaskLogId id) {
		this.id = id;
	}

}
