package com.baoxue.db;

// Generated 2012-11-28 15:32:20 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VTaskLogId generated by hbm2java
 */
@Embeddable
public class VTaskLogId implements java.io.Serializable {

	private String CId;
	private String CTaskId;
	private String CName;
	private String CVersionRegex;
	private Date CCreateTime;
	private boolean CPublish;
	private boolean CDelete;
	private String CDeviceId;
	private Date CTime;
	private String CIp;
	private String CDeviceVersion;

	public VTaskLogId() {
	}

	public VTaskLogId(String CTaskId, String CName, Date CCreateTime,
			boolean CPublish, boolean CDelete) {
		this.CTaskId = CTaskId;
		this.CName = CName;
		this.CCreateTime = CCreateTime;
		this.CPublish = CPublish;
		this.CDelete = CDelete;
	}

	public VTaskLogId(String CId, String CTaskId, String CName,
			String CVersionRegex, Date CCreateTime, boolean CPublish,
			boolean CDelete, String CDeviceId, Date CTime, String CIp,
			String CDeviceVersion) {
		this.CId = CId;
		this.CTaskId = CTaskId;
		this.CName = CName;
		this.CVersionRegex = CVersionRegex;
		this.CCreateTime = CCreateTime;
		this.CPublish = CPublish;
		this.CDelete = CDelete;
		this.CDeviceId = CDeviceId;
		this.CTime = CTime;
		this.CIp = CIp;
		this.CDeviceVersion = CDeviceVersion;
	}

	@Column(name = "C_ID", length = 36)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "C_TASK_ID", nullable = false, length = 36)
	public String getCTaskId() {
		return this.CTaskId;
	}

	public void setCTaskId(String CTaskId) {
		this.CTaskId = CTaskId;
	}

	@Column(name = "C_NAME", nullable = false)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "C_VERSION_REGEX", length = 200)
	public String getCVersionRegex() {
		return this.CVersionRegex;
	}

	public void setCVersionRegex(String CVersionRegex) {
		this.CVersionRegex = CVersionRegex;
	}

	@Column(name = "C_CREATE_TIME", nullable = false, length = 19)
	public Date getCCreateTime() {
		return this.CCreateTime;
	}

	public void setCCreateTime(Date CCreateTime) {
		this.CCreateTime = CCreateTime;
	}

	@Column(name = "C_PUBLISH", nullable = false)
	public boolean isCPublish() {
		return this.CPublish;
	}

	public void setCPublish(boolean CPublish) {
		this.CPublish = CPublish;
	}

	@Column(name = "C_DELETE", nullable = false)
	public boolean isCDelete() {
		return this.CDelete;
	}

	public void setCDelete(boolean CDelete) {
		this.CDelete = CDelete;
	}

	@Column(name = "C_DEVICE_ID", length = 36)
	public String getCDeviceId() {
		return this.CDeviceId;
	}

	public void setCDeviceId(String CDeviceId) {
		this.CDeviceId = CDeviceId;
	}

	@Column(name = "C_TIME", length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Column(name = "C_IP", length = 27)
	public String getCIp() {
		return this.CIp;
	}

	public void setCIp(String CIp) {
		this.CIp = CIp;
	}

	@Column(name = "C_DEVICE_VERSION", length = 30)
	public String getCDeviceVersion() {
		return this.CDeviceVersion;
	}

	public void setCDeviceVersion(String CDeviceVersion) {
		this.CDeviceVersion = CDeviceVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VTaskLogId))
			return false;
		VTaskLogId castOther = (VTaskLogId) other;

		return ((this.getCId() == castOther.getCId()) || (this.getCId() != null
				&& castOther.getCId() != null && this.getCId().equals(
				castOther.getCId())))
				&& ((this.getCTaskId() == castOther.getCTaskId()) || (this
						.getCTaskId() != null && castOther.getCTaskId() != null && this
						.getCTaskId().equals(castOther.getCTaskId())))
				&& ((this.getCName() == castOther.getCName()) || (this
						.getCName() != null && castOther.getCName() != null && this
						.getCName().equals(castOther.getCName())))
				&& ((this.getCVersionRegex() == castOther.getCVersionRegex()) || (this
						.getCVersionRegex() != null
						&& castOther.getCVersionRegex() != null && this
						.getCVersionRegex()
						.equals(castOther.getCVersionRegex())))
				&& ((this.getCCreateTime() == castOther.getCCreateTime()) || (this
						.getCCreateTime() != null
						&& castOther.getCCreateTime() != null && this
						.getCCreateTime().equals(castOther.getCCreateTime())))
				&& (this.isCPublish() == castOther.isCPublish())
				&& (this.isCDelete() == castOther.isCDelete())
				&& ((this.getCDeviceId() == castOther.getCDeviceId()) || (this
						.getCDeviceId() != null
						&& castOther.getCDeviceId() != null && this
						.getCDeviceId().equals(castOther.getCDeviceId())))
				&& ((this.getCTime() == castOther.getCTime()) || (this
						.getCTime() != null && castOther.getCTime() != null && this
						.getCTime().equals(castOther.getCTime())))
				&& ((this.getCIp() == castOther.getCIp()) || (this.getCIp() != null
						&& castOther.getCIp() != null && this.getCIp().equals(
						castOther.getCIp())))
				&& ((this.getCDeviceVersion() == castOther.getCDeviceVersion()) || (this
						.getCDeviceVersion() != null
						&& castOther.getCDeviceVersion() != null && this
						.getCDeviceVersion().equals(
								castOther.getCDeviceVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCId() == null ? 0 : this.getCId().hashCode());
		result = 37 * result
				+ (getCTaskId() == null ? 0 : this.getCTaskId().hashCode());
		result = 37 * result
				+ (getCName() == null ? 0 : this.getCName().hashCode());
		result = 37
				* result
				+ (getCVersionRegex() == null ? 0 : this.getCVersionRegex()
						.hashCode());
		result = 37
				* result
				+ (getCCreateTime() == null ? 0 : this.getCCreateTime()
						.hashCode());
		result = 37 * result + (this.isCPublish() ? 1 : 0);
		result = 37 * result + (this.isCDelete() ? 1 : 0);
		result = 37 * result
				+ (getCDeviceId() == null ? 0 : this.getCDeviceId().hashCode());
		result = 37 * result
				+ (getCTime() == null ? 0 : this.getCTime().hashCode());
		result = 37 * result
				+ (getCIp() == null ? 0 : this.getCIp().hashCode());
		result = 37
				* result
				+ (getCDeviceVersion() == null ? 0 : this.getCDeviceVersion()
						.hashCode());
		return result;
	}

}
